apiVersion: apps/v1
kind: Deployment
metadata:
  name: async-compare-deployment
spec:
  selector:
    matchLabels:
      app: async-compare-api
  template:
    metadata:
      labels:
        app: async-compare-api
    spec:
      containers:
      - name: async-compare-api
        image: rafaelricardomo/async-compare-api:{{tag}}        
        ports:
        - containerPort: 80
